/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_szktas_eos_EOSBinder_EOSNative */

#ifndef _Included_io_szktas_eos_EOSBinder_EOSNative
#define _Included_io_szktas_eos_EOSBinder_EOSNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    SetLogging
 * Signature: (Ljava/util/function/BiConsumer;)V
 */
JNIEXPORT void JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_SetLogging
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    getPUID
 * Signature: (Ljava/lang/String;Ljava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_getPUID
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    SetNameGetter
 * Signature: (Ljava/util/function/Supplier;)V
 */
JNIEXPORT void JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_SetNameGetter
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_init
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    initConnectionHandle
 * Signature: (DLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_initConnectionHandle
  (JNIEnv *, jclass, jdouble, jstring, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    setNetworkStatus
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_setNetworkStatus
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    subscribeIncomingConnectionRequestHandler
 * Signature: (Lorg/apache/logging/log4j/util/TriConsumer;)V
 */
JNIEXPORT void JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_subscribeIncomingConnectionRequestHandler
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    subscribeIncomingConnectionRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_subscribeIncomingConnectionRequest
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    subscribeEstablishedConnectionRequestHandler
 * Signature: (Lorg/apache/logging/log4j/util/TriConsumer;)V
 */
JNIEXPORT void JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_subscribeEstablishedConnectionRequestHandler
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    subscribeEstablishedConnectionRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_subscribeEstablishedConnectionRequest
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    subscribeInterruptConnectionRequestHandler
 * Signature: (Lorg/apache/logging/log4j/util/TriConsumer;)V
 */
JNIEXPORT void JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_subscribeInterruptConnectionRequestHandler
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    subscribeInterruptConnectionRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_subscribeInterruptConnectionRequest
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    subscribeCloseConnectionRequestHandler
 * Signature: (Lorg/apache/logging/log4j/util/TriConsumer;)V
 */
JNIEXPORT void JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_subscribeCloseConnectionRequestHandler
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    subscribeCloseConnectionRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_subscribeCloseConnectionRequest
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    connectOrAccept
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_connectOrAccept
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    close
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_close
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    send
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;B[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_send
  (JNIEnv *, jclass, jstring, jstring, jstring, jbyte, jbyteArray);

/*
 * Class:     io_szktas_eos_EOSBinder_EOSNative
 * Method:    registerReceiveCallbackFor
 * Signature: (Ljava/lang/String;Lio/szktas/eos/Util/PacketConsumer;)V
 */
JNIEXPORT void JNICALL Java_io_szktas_eos_EOSBinder_EOSNative_registerReceiveCallbackFor
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
