name: Build Native Binary for EOS Service Wrapper

on:
  workflow_dispatch:
    inputs:
      debug:
        description: "Debug build"
        required: false
        type: boolean
        default: false

jobs:
  build_native:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v6

      - name: Download JNI Header
        run: git clone https://github.com/Casterlabs/jni-headers.git

      - name: Download SDK
        run: |
          mkdir -p EOSSDK
          curl -L "https://onlineservices.epicgames.com/api/cosmos/sdk/download?archive_id=870&archive_type=sdk" --output EOSSDK/out.zip

      - name: Unzip SDK
        run: unzip EOSSDK/out.zip -d EOSSDK

      - name: Install Compilers in Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt install clang lld llvm gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          curl -L "https://github.com/mstorsjo/llvm-mingw/releases/download/20260602/llvm-mingw-20260602-msvcrt-ubuntu-22.04-x86_64.tar.xz" --output out.tar.xz
          tar -Jxvf out.tar.xz
          echo "llvm-mingw-20260602-msvcrt-ubuntu-22.04-x86_64/bin" >> $GITHUB_PATH

      - name: Install Dependencies in MacOS
        if: runner.os == 'macOS'
        run: |
          git clone https://github.com/fmtlib/fmt.git

      - name: Compile (Linux & Windows)
        if: runner.os == 'Linux'
        run: |
          export DO_DEBUG_ARG=""
          if [ "${{ inputs.debug }}" == "true" ]; then
            export DO_DEBUG_ARG=-g
          fi
          clang++ --target=x86_64-linux-gnu -O3 -march=x86-64-v2 -fno-plt -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti $DO_DEBUG_ARG -IEOSSDK/SDK/Include -I"jni-headers/versions/17/include" -I"jni-headers/versions/17/include/linux" -std=c++20 -static-libgcc -static-libstdc++ -fPIC -shared -L./EOSSDK/SDK/Bin -l:libEOSSDK-Linux-Shipping.so ${{ github.workspace }}/src/main/cpp/Src/Main.cpp -o linuxx64.so
          echo "Start Arm"
          clang++ --target=aarch64-linux-gnu --sysroot=/usr/aarch64-linux-gnu -O3 -fno-plt -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti $DO_DEBUG_ARG -IEOSSDK/SDK/Include -I"jni-headers/versions/17/include" -I"jni-headers/versions/17/include/linux" -std=c++20 -static-libgcc -static-libstdc++ -fPIC -shared -L./EOSSDK/SDK/Bin -l:libEOSSDK-LinuxArm64-Shipping.so ${{ github.workspace }}/src/main/cpp/Src/Main.cpp -o linuxarm64.so
          x86_64-w64-mingw32-clang++ -O3 -march=x86-64-v2 -fno-plt -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti $DO_DEBUG_ARG -IEOSSDK/SDK/Include -I"jni-headers/versions/17/include" -I"jni-headers/versions/17/include/win32" -std=c++20 -static-libgcc -static-libstdc++ -static -shared -L./EOSSDK/SDK/Bin -l:EOSSDK-Win64-Shipping.dll ${{ github.workspace }}/src/main/cpp/Src/Main.cpp -o mainx64.dll
          aarch64-w64-mingw32-clang++ --target=aarch64-w64-mingw32 -fuse-ld=lld -O3 -fno-plt -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti $DO_DEBUG_ARG -IEOSSDK/SDK/Include -I"jni-headers/versions/17/include" -I"jni-headers/versions/17/include/win32" -std=c++20 -static-libgcc -static-libstdc++ -static -shared -L./EOSSDK/SDK/Bin -l:EOSSDK-Win64-Shippingarm64.dll ${{ github.workspace }}/src/main/cpp/Src/Main.cpp -o mainarm64.dll

      - name: Compile (MacOS)
        if: runner.os == 'macOS'
        run: |
          export MACOSX_DEPLOYMENT_TARGET=11.0
          export DO_DEBUG_ARG=""
          if [ "${{ inputs.debug }}" == "true" ]; then
            export DO_DEBUG_ARG=-g
          fi
          clang++ -O3 -arch x86_64 -fno-plt -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti $DO_DEBUG_ARG -Ifmt/include -IEOSSDK/SDK/Include -I"jni-headers/versions/17/include" -I"jni-headers/versions/17/include/darwin" -std=c++20 -dynamiclib -fPIC -install_name @rpath/eosp2p_mac.dylib -L./EOSSDK/SDK/Bin -lEOSSDK-Mac-Shipping ${{ github.workspace }}/src/main/cpp/Src/Main.cpp -o macx64.dylib
          clang++ -O3 -arch arm64 -fno-plt -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti $DO_DEBUG_ARG -Ifmt/include -IEOSSDK/SDK/Include -I"jni-headers/versions/17/include" -I"jni-headers/versions/17/include/darwin" -std=c++20 -dynamiclib -fPIC -install_name @rpath/eosp2p_mac.dylib -L./EOSSDK/SDK/Bin -lEOSSDK-Mac-Shipping ${{ github.workspace }}/src/main/cpp/Src/Main.cpp -o macarm64.dylib
          lipo -create -output mac.dylib macx64.dylib macarm64.dylib
          

      - name: Patch (Linux & Windows)
        if: runner.os == 'Linux'
        run: |
          python3 ${{ github.workspace }}/src/main/python/edit_import_table.py mainx64.dll winx64.dll EOSSDK-Win64-Shipping.dll eosp2p_eos.dll
          python3 ${{ github.workspace }}/src/main/python/edit_import_table.py mainarm64.dll winarm64.dll EOSSDK-Win64-Shippingarm64.dll eosp2p_eos.dll
          patchelf --replace-needed libEOSSDK-Linux-Shipping.so eosp2p_eos.so linuxx64.so
          patchelf --replace-needed libEOSSDK-LinuxArm64-Shipping.so eosp2p_eos.so linuxarm64.so

      - name: Patch (MacOS)
        if: runner.os == 'macOS'
        run: |
          install_name_tool -change @rpath/libEOSSDK-Mac-Shipping.dylib @rpath/eosp2p_eos.dylib mac.dylib
          install_name_tool -id @rpath/eosp2p_eos.dylib EOSSDK/SDK/Bin/libEOSSDK-Mac-Shipping.dylib

      - name: Upload Artifact (Linux & Windows)
        uses: actions/upload-artifact@v7
        if: runner.os == 'Linux'
        with:
          name: linux-and-win
          path: |
            linuxx64.so
            linuxarm64.so
            winx64.dll
            winarm64.dll

      - name: Upload Artifact (MacOS)
        uses: actions/upload-artifact@v7
        if: runner.os == 'macOS'
        with:
          name: macos
          path: |
            mac.dylib
            EOSSDK/SDK/Bin/libEOSSDK-Mac-Shipping.dylib
