name: Build Native Binary for EOS Service Wrapper

on:
  workflow_dispatch:
    inputs:
      debug:
        description: "Debug build"
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      debug:
        description: "Debug build"
        required: false
        type: boolean
        default: false

jobs:
  build_native:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            zigkey: x86_64
          - os: ubuntu-24.04-arm
            zigkey: aarch64

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Setup Version Info
        run: |
          export version=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)
          export name=$(grep '^mod_id=' gradle.properties | cut -d'=' -f2)
          
          echo "version=$version" >> $GITHUB_ENV
          echo "name=$name" >> $GITHUB_ENV

      - name: Download SDK
        run: |
          mkdir -p EOSSDK
          curl -L "https://onlineservices.epicgames.com/api/cosmos/sdk/download?archive_id=870&archive_type=sdk" --output EOSSDK/out.zip

      - name: Unzip SDK
        run: unzip EOSSDK/out.zip -d EOSSDK

      - name: Install Compilers in Linux
        if: runner.os == 'Linux'
        run: |
          curl https://ziglang.org/builds/zig-${{ matrix.zigkey }}-linux-0.17.0-dev.813+2153f8143.tar.xz --output zig.tar.xz
          tar -Jxvf zig.tar.xz
          echo "zig-x86_64-linux-0.17.0-dev.813+2153f8143" >> $GITHUB_PATH

      - name: Install Cross-Compiler for Windows in Linux
        if: runner.os == 'Linux' && runner.arch == 'X64'
        run: |
          curl -L "https://github.com/mstorsjo/llvm-mingw/releases/download/20260602/llvm-mingw-20260602-msvcrt-ubuntu-22.04-x86_64.tar.xz" --output out.tar.xz
          tar -Jxvf out.tar.xz
          echo "llvm-mingw-20260602-msvcrt-ubuntu-22.04-x86_64/bin" >> $GITHUB_PATH

      - uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create Header File
        working-directory: ${{ github.workspace }}
        run: |
          chmod +x ./gradlew
          ./gradlew generateHeaders
          ./gradlew --stop
          

      - name: Compile x64
        if: runner.os == 'Linux' && runner.arch == 'X64'
        run: |
          export DO_DEBUG_ARG=""
          if [ "${{ inputs.debug }}" == "true" ]; then
            export DO_DEBUG_ARG=-g3 -Wall -Wextra -Wpedantic
          fi
          zig c++ --target=x86_64-linux-gnu.2.31 -O3 -march=x86_64_v2 -fno-plt -ffunction-sections -fdata-sections -fno-rtti $DO_DEBUG_ARG -IEOSSDK/SDK/Include -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include" -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include/linux" -std=c++20 -static-libgcc -static-libstdc++ -fPIC -shared -L./EOSSDK/SDK/Bin -l:libEOSSDK-Linux-Shipping.so ${{ github.workspace }}/src/main/cpp/Src/Main.cpp ${{ github.workspace }}/src/main/cpp/Src/kcp/ikcp.c -o linuxx64.so
          x86_64-w64-mingw32-clang++ -static -O3 -march=x86-64-v2 -fno-plt -ffunction-sections -fdata-sections -fno-rtti $DO_DEBUG_ARG -IEOSSDK/SDK/Include -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include" -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include/win32" -std=c++20 -static-libgcc -static-libstdc++ -static -shared -L./EOSSDK/SDK/Bin -l:EOSSDK-Win64-Shipping.dll ${{ github.workspace }}/src/main/cpp/Src/Main.cpp ${{ github.workspace }}/src/main/cpp/Src/kcp/ikcp.c -o mainx64.dll
          aarch64-w64-mingw32-clang++ --target=aarch64-w64-mingw32 -fuse-ld=lld -static -O3 -fno-plt -ffunction-sections -fdata-sections -fno-rtti $DO_DEBUG_ARG -IEOSSDK/SDK/Include -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include" -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include/win32" -std=c++20 -static-libgcc -static-libstdc++ -static -shared -L./EOSSDK/SDK/Bin -l:EOSSDK-Win64-Shippingarm64.dll ${{ github.workspace }}/src/main/cpp/Src/Main.cpp ${{ github.workspace }}/src/main/cpp/Src/kcp/ikcp.c -o mainarm64.dll

      - name: Compile ARM64
        if: runner.os == 'Linux' && runner.arch == 'ARM64'
        run: |
          export DO_DEBUG_ARG=""
          if [ "${{ inputs.debug }}" == "true" ]; then
            export DO_DEBUG_ARG=-g3 -Wall -Wextra -Wpedantic
          fi
          zig c++ --target=aarch64-linux-gnu.2.31 -O3 -fno-plt -ffunction-sections -fdata-sections -fno-rtti $DO_DEBUG_ARG -IEOSSDK/SDK/Include -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include" -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include/linux" -std=c++20 -static-libgcc -static-libstdc++ -fPIC -shared -L./EOSSDK/SDK/Bin -l:libEOSSDK-LinuxArm64-Shipping.so ${{ github.workspace }}/src/main/cpp/Src/Main.cpp ${{ github.workspace }}/src/main/cpp/Src/kcp/ikcp.c -o linuxarm64.so

      - name: Compile (MacOS)
        if: runner.os == 'macOS'
        run: |
          export DO_DEBUG_ARG=""
          if [ "${{ inputs.debug }}" == "true" ]; then
            export DO_DEBUG_ARG=-g3 -Wall -Wextra -Wpedantic
          fi
          export MACOSX_DEPLOYMENT_TARGET=10.15
          clang++ -O3 -arch x86_64 -fno-plt -ffunction-sections -fdata-sections -fno-rtti $DO_DEBUG_ARG -I${{ github.workspace }}/src/main/cpp/Src/fmt/include -IEOSSDK/SDK/Include -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include" -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include/darwin" -std=c++20 -dynamiclib -fPIC -install_name @rpath/${{ env.name }}_mac.dylib -L./EOSSDK/SDK/Bin -lEOSSDK-Mac-Shipping ${{ github.workspace }}/src/main/cpp/Src/Main.cpp ${{ github.workspace }}/src/main/cpp/Src/kcp/ikcp.c -o macx64.dylib
          export MACOSX_DEPLOYMENT_TARGET=11.0
          clang++ -O3 -arch arm64 -fno-plt -ffunction-sections -fdata-sections -fno-rtti $DO_DEBUG_ARG -I${{ github.workspace }}/src/main/cpp/Src/fmt/include -IEOSSDK/SDK/Include -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include" -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include/darwin" -std=c++20 -dynamiclib -fPIC -install_name @rpath/${{ env.name }}_mac.dylib -L./EOSSDK/SDK/Bin -lEOSSDK-Mac-Shipping ${{ github.workspace }}/src/main/cpp/Src/Main.cpp ${{ github.workspace }}/src/main/cpp/Src/kcp/ikcp.c -o macarm64.dylib
          lipo -create -output mac.dylib macx64.dylib macarm64.dylib
          

      - name: Patch x64
        if: runner.os == 'Linux' && runner.arch == 'X64'
        run: |
          python3 ${{ github.workspace }}/src/main/python/edit_import_table.py mainx64.dll winx64.dll EOSSDK-Win64-Shipping.dll ${{ env.name }}_eos.dll
          python3 ${{ github.workspace }}/src/main/python/edit_import_table.py mainarm64.dll winarm64.dll EOSSDK-Win64-Shippingarm64.dll ${{ env.name }}_eos.dll
          patchelf --replace-needed libEOSSDK-Linux-Shipping.so ${{ env.name }}_eos.so linuxx64.so

      - name: Patch ARM64
        if: runner.os == 'Linux' && runner.arch == 'ARM64'
        run: patchelf --replace-needed libEOSSDK-LinuxArm64-Shipping.so ${{ env.name }}_eos.so linuxarm64.so

      - name: Patch (MacOS)
        if: runner.os == 'macOS'
        run: |
          install_name_tool -change @rpath/libEOSSDK-Mac-Shipping.dylib @rpath/${{ env.name }}_eos.dylib mac.dylib
          codesign --force --sign - --options=runtime --deep mac.dylib
          install_name_tool -id @rpath/${{ env.name }}_eos.dylib EOSSDK/SDK/Bin/libEOSSDK-Mac-Shipping.dylib

      - name: Upload Artifact (x64)
        uses: actions/upload-artifact@v7
        if: runner.os == 'Linux' && runner.arch == 'X64'
        with:
          name: linux-and-win-x64
          path: |
            linuxx64.so
            linuxarm64.so
            winx64.dll
            winarm64.dll

      - name: Upload Artifact (arm64)
        uses: actions/upload-artifact@v7
        if: runner.os == 'Linux' && runner.arch == 'ARM64'
        with:
          name: linux-arm64
          path: |
            linuxarm64.so

      - name: Upload Artifact (MacOS)
        uses: actions/upload-artifact@v7
        if: runner.os == 'macOS'
        with:
          name: macos
          path: |
            mac.dylib
            EOSSDK/SDK/Bin/libEOSSDK-Mac-Shipping.dylib
