name: Build Native Binary for EOS Service Wrapper

on:
  workflow_dispatch:
    inputs:
      debug:
        description: "Debug build"
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      debug:
        description: "Debug build"
        required: false
        type: boolean
        default: false

jobs:
  build_native:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build: linux
          - os: ubuntu-24.04-arm
            build: linux
          - os: ubuntu-latest
            build: win
            compre: x86_64
            spec: -march=x86-64-v2
            subpad: ''
            fnpad: x64
          - os: ubuntu-latest
            build: win
            compre: aarch64
            spec: --target=aarch64-w64-mingw32
            subpad: arm64
            fnpad: arm64
          - os: ubuntu-latest
            build: android
            compre: aarch64
          - os: ubuntu-latest
            build: android
            compre: x86_64
          - os: macos-latest

    env:
      DO_DEBUG_ARG: ${{ case( inputs.debug, '-g3 -Wall -Wextra -Wpedantic', '-fvisibility=hidden -fvisibility-inlines-hidden') }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Setup Version Info
        run: |
          export version=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)
          export name=$(grep '^mod_id=' gradle.properties | cut -d'=' -f2)
          
          echo "version=$version" >> $GITHUB_ENV
          echo "name=$name" >> $GITHUB_ENV

      - name: Download SDK
        run: |
          mkdir -p EOSSDK
          curl -L "https://onlineservices.epicgames.com/api/cosmos/sdk/download?archive_id=${{ case(matrix.build == 'android', '871', '870') }}&archive_type=${{ case(matrix.build == 'android', 'android', 'sdk') }}" --output EOSSDK/out.zip

      - name: Unzip SDK
        run: unzip EOSSDK/out.zip -d EOSSDK

      - name: Further unzip SDK
        if: runner.os == 'Linux' && matrix.build == 'android'
        run: |
          mkdir -p ELIB
          unzip EOSSDK/SDK/Bin/Android/static-stdc++/aar/eossdk-StaticSTDC-release.aar -d ELIB 

      - name: Initialize Variables
        if: runner.os == 'Linux' && matrix.build == 'linux'
        run: |
          rarch="${{ runner.arch }}"
          echo "zigkey=${{ case(runner.arch == 'X64', 'x86_64', 'aarch64') }}" >> $GITHUB_ENV
          echo "march=${{ case(runner.arch == 'X64', '-march=x86_64_v2', '') }}" >> $GITHUB_ENV
          echo "arch=${rarch,,}" >> $GITHUB_ENV
          echo "archpad=${{ case(runner.arch == 'X64', '', 'Arm64') }}" >> $GITHUB_ENV

      - name: Initialize Compiler Args
        if: runner.os == 'Linux' && matrix.build != 'win' && !inputs.debug
        run: |
          echo "DO_DEBUG_ARG=$DO_DEBUG_ARG -Wl,--version-script=${{ github.workspace }}/src/main/cpp/Src/linker.script" >> $GITHUB_ENV

      - name: Initialize Variables
        if: runner.os == 'Linux' && matrix.build == 'android'
        run: |
          echo "lpad=${{ case(matrix.compre == 'x86_64', 'x86_64', 'arm64-v8a') }}" >> $GITHUB_ENV
          echo "arch=${{ case(matrix.compre == 'x86_64', 'x64', 'arm64') }}" >> $GITHUB_ENV

      - name: Install Compilers in Linux
        if: runner.os == 'Linux' && matrix.build == 'linux'
        run: |
          curl https://ziglang.org/builds/zig-${{ env.zigkey }}-linux-0.17.0-dev.813+2153f8143.tar.xz --output zig.tar.xz
          tar -Jxvf zig.tar.xz
          echo "zig-${{ env.zigkey }}-linux-0.17.0-dev.813+2153f8143" >> $GITHUB_PATH

      - name: Install Cross-Compiler for Windows in Linux
        if: runner.os == 'Linux' && matrix.build == 'win'
        run: |
          curl -L "https://github.com/mstorsjo/llvm-mingw/releases/download/20260602/llvm-mingw-20260602-msvcrt-ubuntu-22.04-x86_64.tar.xz" --output out.tar.xz
          tar -Jxvf out.tar.xz
          echo "llvm-mingw-20260602-msvcrt-ubuntu-22.04-x86_64/bin" >> $GITHUB_PATH

      - name: Download Command Line Tools for Android in Linux
        if: runner.os == 'Linux' && matrix.build == 'android'
        run: |
          mkdir -p android-sdk/cmdline-tools
          curl -L https://dl.google.com/android/repository/commandlinetools-linux-14742923_latest.zip --output clt.zip
          unzip clt.zip
          mv cmdline-tools android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=android-sdk" >> $GITHUB_ENV
          echo "android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          
      - name: Install NDK in Linux
        if: runner.os == 'Linux' && matrix.build == 'android'
        run: |
          (yes || true) | sdkmanager --licenses
          (yes || true) | sdkmanager "ndk;27.0.12077973"
          export NDK_HOME=$ANDROID_HOME/ndk/27.0.12077973
          echo "NDK_HOME=$NDK_HOME" >> $GITHUB_ENV
          echo "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/" >> $GITHUB_PATH
          echo "SYSROOT=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot" >> $GITHUB_ENV
          echo "NDK_CPP_INCLUDE=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1" >> $GITHUB_ENV
          echo "NDK_INCLUDE=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include" >> $GITHUB_ENV
          echo "NDK_LIB=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/${{ matrix.compre }}-linux-android/24" >> $GITHUB_ENV

      - uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create Header File
        working-directory: ${{ github.workspace }}
        run: |
          chmod +x ./gradlew
          ./gradlew generateHeaders
          ./gradlew --stop

      - name: Compile Linux
        if: runner.os == 'Linux' && matrix.build == 'linux'
        run: |
          zig c++ --target=${{ env.zigkey }}-linux-gnu.2.31 -O3 ${{ env.march }} -fno-plt -ffunction-sections -fdata-sections -fno-rtti ${{ env.DO_DEBUG_ARG }} -IEOSSDK/SDK/Include -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include" -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include/linux" -std=c++20 -static-libgcc -static-libstdc++ -Wl,--as-needed -pthread -fPIC -shared -c -L./EOSSDK/SDK/Bin -lEOSSDK-Linux${{ env.archpad }}-Shipping ${{ github.workspace }}/src/main/cpp/Src/Main.cpp -o linux_main.o
          zig cc --target=${{ env.zigkey }}-linux-gnu.2.31 -O3 ${{ env.march }} -fno-plt -ffunction-sections -fdata-sections -fno-rtti ${{ env.DO_DEBUG_ARG }} -IEOSSDK/SDK/Include -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include" -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include/linux" -static-libgcc -static-libstdc++ -Wl,--as-needed -pthread -fPIC -shared -c -L./EOSSDK/SDK/Bin -lEOSSDK-Linux${{ env.archpad }}-Shipping ${{ github.workspace }}/src/main/cpp/Src/kcp/ikcp.c -o linux_c.o
          zig c++ --target=${{ env.zigkey }}-linux-gnu.2.31 -O3 ${{ env.march }} -fno-plt -ffunction-sections -fdata-sections -fno-rtti ${{ env.DO_DEBUG_ARG }} -IEOSSDK/SDK/Include -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include" -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include/linux" -std=c++20 -static-libgcc -static-libstdc++ -Wl,--as-needed -pthread -fPIC -shared -L./EOSSDK/SDK/Bin -lEOSSDK-Linux${{ env.archpad }}-Shipping linux_c.o linux_main.o -o linux${{ env.arch }}.so

      - name: Compile Android
        if: runner.os == 'Linux' && matrix.build == 'android'
        run: |
          clang++ --sysroot=${{ env.SYSROOT }} -DANDROID_STL=c++_static -stdlib=libc++ -static-libstdc++ -DANDROID -D__ANDROID__ -D_GNU_SOURCE -target ${{ matrix.compre }}-linux-android24 -O3 -stdlib=libc++ -fno-plt -ffunction-sections -fdata-sections -fno-rtti ${{ env.DO_DEBUG_ARG }} -IEOSSDK/SDK/Include -std=c++20 -Wl,--as-needed -pthread -fPIC -landroid -llog -lm -lc -ldl -shared -c -LELIB/jni/${{ env.lpad }} -lEOSSDK ${{ github.workspace }}/src/main/cpp/Src/Main.cpp -o android_main.o
          clang --sysroot=${{ env.SYSROOT }} -DANDROID_STL=c++_static -DANDROID -D__ANDROID__ -D_GNU_SOURCE -target ${{ matrix.compre }}-linux-android24 -O3 -stdlib=libc++ -fno-plt -ffunction-sections -fdata-sections -fno-rtti ${{ env.DO_DEBUG_ARG }} -IEOSSDK/SDK/Include -Wl,--as-needed -pthread -fPIC -landroid -llog -lm -lc -ldl -shared -c -LELIB/jni/${{ env.lpad }} -lEOSSDK ${{ github.workspace }}/src/main/cpp/Src/kcp/ikcp.c -o android_c.o
          clang++ --sysroot=${{ env.SYSROOT }} -DANDROID_STL=c++_static -stdlib=libc++ -static-libstdc++ -DANDROID -D__ANDROID__ -D_GNU_SOURCE -target ${{ matrix.compre }}-linux-android24 -O3 -stdlib=libc++ -fno-plt -ffunction-sections -fdata-sections -fno-rtti ${{ env.DO_DEBUG_ARG }} -IEOSSDK/SDK/Include -std=c++20 -Wl,--as-needed android_main.o android_c.o -o android${{ env.arch }}.so -pthread -fPIC -shared -LELIB/jni/${{ env.lpad }} -lEOSSDK -landroid -llog -lm -lc -ldl

      - name: Compile Win
        if: runner.os == 'Linux' && matrix.build == 'win'
        run: |
          ${{ matrix.compre }}-w64-mingw32-clang++ ${{ matrix.spec }} -fuse-ld=lld -static -O3 -fno-plt -ffunction-sections -fdata-sections -fno-rtti ${{ env.DO_DEBUG_ARG }} -IEOSSDK/SDK/Include -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include" -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include/win32" -std=c++20 -static-libgcc -static-libstdc++ -static -shared -L./EOSSDK/SDK/Bin -l:EOSSDK-Win64-Shipping${{ matrix.subpad }}.dll ${{ github.workspace }}/src/main/cpp/Src/Main.cpp ${{ github.workspace }}/src/main/cpp/Src/kcp/ikcp.c -o main.dll

      - name: Compile MacOS
        if: runner.os == 'macOS'
        run: |
          export MACOSX_DEPLOYMENT_TARGET=10.15
          clang++ -O3 -arch x86_64 -fno-plt -ffunction-sections -fdata-sections -fno-rtti ${{ env.DO_DEBUG_ARG }} -I${{ github.workspace }}/src/main/cpp/Src/fmt/include -IEOSSDK/SDK/Include -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include" -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include/darwin" -std=c++20 -dynamiclib -fPIC -install_name @rpath/${{ env.name }}_mac.dylib -L./EOSSDK/SDK/Bin -lEOSSDK-Mac-Shipping ${{ github.workspace }}/src/main/cpp/Src/Main.cpp ${{ github.workspace }}/src/main/cpp/Src/kcp/ikcp.c -o macx64.dylib
          export MACOSX_DEPLOYMENT_TARGET=11.0
          clang++ -O3 -arch arm64 -fno-plt -ffunction-sections -fdata-sections -fno-rtti ${{ env.DO_DEBUG_ARG }} -I${{ github.workspace }}/src/main/cpp/Src/fmt/include -IEOSSDK/SDK/Include -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include" -I"${{ github.workspace }}/src/main/cpp/Src/jni-headers/versions/17/include/darwin" -std=c++20 -dynamiclib -fPIC -install_name @rpath/${{ env.name }}_mac.dylib -L./EOSSDK/SDK/Bin -lEOSSDK-Mac-Shipping ${{ github.workspace }}/src/main/cpp/Src/Main.cpp ${{ github.workspace }}/src/main/cpp/Src/kcp/ikcp.c -o macarm64.dylib
          lipo -create -output mac.dylib macx64.dylib macarm64.dylib

      - name: Patch windows
        if: runner.os == 'Linux' && matrix.build == 'win'
        run: |
          python3 ${{ github.workspace }}/src/main/python/edit_import_table.py main.dll win${{ matrix.fnpad }}.dll EOSSDK-Win64-Shipping${{ matrix.subpad }}.dll ${{ env.name }}_eos.dll

      - name: Patch Linux
        if: runner.os == 'Linux' && matrix.build == 'linux'
        run: |
          patchelf --set-soname ${{ env.name }}_eos.so EOSSDK/SDK/Bin/libEOSSDK-Linux${{ env.archpad }}-Shipping.so
          patchelf --replace-needed libEOSSDK-Linux${{ env.archpad }}-Shipping.so ${{ env.name }}_eos.so linux${{ env.arch }}.so
          cp EOSSDK/SDK/Bin/libEOSSDK-Linux${{ env.archpad }}-Shipping.so .

      - name: Patch Android
        if: runner.os == 'Linux' && matrix.build == 'android'
        run: |
          patchelf --set-soname ${{ env.name }}_eos.so ELIB/jni/${{ env.lpad }}/libEOSSDK.so
          patchelf --replace-needed libEOSSDK.so ${{ env.name }}_eos.so android${{ env.arch }}.so
          cp ELIB/jni/${{ env.lpad }}/libEOSSDK.so libEOSSDK-A${{ env.arch }}.so

      - name: Patch MacOS
        if: runner.os == 'macOS'
        run: |
          install_name_tool -change @rpath/libEOSSDK-Mac-Shipping.dylib @rpath/${{ env.name }}_eos.dylib mac.dylib
          codesign --force --sign - --options=runtime --deep mac.dylib
          install_name_tool -id @rpath/${{ env.name }}_eos.dylib EOSSDK/SDK/Bin/libEOSSDK-Mac-Shipping.dylib

      - name: Install Strip Utils in Linux
        if: runner.os == 'Linux' && matrix.build == 'linux' && !inputs.debug
        run: |
          apt-get update
          apt-get -y install llvm 

      - name: Strip (Linux)
        if: runner.os == 'Linux' && matrix.build != 'win' && !inputs.debug
        run: |
          llvm-strip --strip-unneeded ${{ matrix.build }}${{ env.arch }}.so
          llvm-strip --strip-unneeded libEOSSDK-${{ case(matrix.build == 'linux', format('Linux{0}-Shipping', env.archpad), format('A{0}', env.arch)) }}.so

      - name: Strip (MacOS)
        if: runner.os == 'macOS' && !inputs.debug
        run: |
          strip -x mac.dylib
          strip -x EOSSDK/SDK/Bin/libEOSSDK-Mac-Shipping.dylib

      - name: Upload Artifact (Windows)
        uses: actions/upload-artifact@v7
        if: runner.os == 'Linux' && matrix.build == 'win'
        with:
          name: win-${{ matrix.fnpad }}
          path: |
            win${{ matrix.fnpad }}.dll

      - name: Upload Artifact (Linux / Android)
        uses: actions/upload-artifact@v7
        if: runner.os == 'Linux' && matrix.build != 'win'
        with:
          name: ${{ matrix.build }}-${{ env.arch }}
          path: |
            ${{ matrix.build }}${{ env.arch }}.so
            libEOSSDK-A${{ env.arch }}.so
            libEOSSDK-Linux${{ env.archpad }}-Shipping.so

      - name: Upload Artifact (MacOS)
        uses: actions/upload-artifact@v7
        if: runner.os == 'macOS'
        with:
          name: macos
          path: |
            mac.dylib
            EOSSDK/SDK/Bin/libEOSSDK-Mac-Shipping.dylib
