name: Build Mod

on:
  workflow_dispatch:
    inputs:
      debug:
        description: "Debug build"
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      debug:
        description: "Debug build"
        required: false
        type: boolean
        default: false

jobs:
  build_native:
    uses: ./.github/workflows/build_native.yml
    with:
      debug: ${{ inputs.debug }}

  build_mod:
    runs-on: ubuntu-latest
    needs: build_native
    defaults:
      run:
        shell: bash

    steps:
      - name: Create Binary Folder
        run: |
          mkdir -p ${{ github.workspace }}/src/main/resources/META-INF/binder
          mkdir binder_temp

      - name: Fetch Binary
        uses: actions/download-artifact@v8
        with:
          path: binder-temp

      - run: find binder_temp -type f \( -name "*.dll" -o -name "*.so" -o -name "*.dylib"\) -exec mv -t ${{ github.workspace }}/src/main/resources/META-INF/binder {} +

      - name: Check Folder
        if: inputs.debug
        run:
          ls -R ${{ github.workspace }}/src/main/resources/META-INF/binder